name: Deploy Frontend to Azure Web App

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pos_app_frontend/**'
      - '.github/workflows/azure-webapps-node.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tech0-gen8-step4-pos-app-59
  AZURE_WEBAPP_PACKAGE_PATH: pos_app_frontend
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: npm ci

      - name: Build
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: https://tech0-gen8-step4-pos-app-60.azurewebsites.net/api

      - name: Prepare deployment
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          cp -r .next/standalone/* .
          cp -r .next/static .next/
          cp -r public .
          rm -rf node_modules
          zip -r ../deployment.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip deployment.zip -d deploy

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISH_PROFILE }}
          package: deploy 